project_id = "toxucscjfmaoayircihp"

[functions.create-booking-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-meeting-confirmation]
verify_jwt = false

[functions.invite-travelers]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.create-meeting-booking]
verify_jwt = false

[functions.create-trip-booking]
verify_jwt = false

[functions.app-dashboard]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = false

[functions.create-altapay-payment]
verify_jwt = false
